### ISSUE TITLE
Quarkus compilation problems

### ISSUE THREAD

**Issue by Andro999b** [nats-io/nats.java#1259]
### Observed behavior

Not able to build native executables with GraalVM native build

### Expected behavior

Native build support

### Server and client version

Client lib: 2.20.4

### Steps to reproduce

Run graalvm native build with jnat client in dependencies

Several thing make impossible to use Native Build compilation:

Improper use of static Random/SecureRandom (static initialization) in: src/main/java/io/nats/client/support/RandomUtils.java
Usage of `net.i2p.crypto:eddsa:0.3.0` that relies on `sun.security.x509.X509Key`.

More details:

```
Error: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected. If these objects should not be stored in the image heap, you can use 

    '--trace-object-instantiation=java.security.SecureRandom'

to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with 

    '--initialize-at-run-time=<culprit>'

to prevent the instantiation of the object.
The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  trying to constant fold static field io.nats.client.support.RandomUtils.SRAND
    at ua.mil.steel.ornament.commons.broker.nats.NatsSSLContextUtil.createSSLContext(NatsSSLContextUtil.java:79)
  parsing method ua.mil.steel.ornament.commons.broker.nats.NatsSSLContextUtil.createSSLContext(NatsSSLContextUtil.java:25) reachable via the parsing context
    at static root method.(Unknown Source)


Error: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected. If these objects should not be stored in the image heap, you can use 

    '--trace-object-instantiation=java.util.Random'

to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with 

    '--initialize-at-run-time=<culprit>'

to prevent the instantiation of the object.
The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  trying to constant fold static field io.nats.client.support.RandomUtils.PRAND
    at io.nats.client.NUID.<init>(NUID.java:77)
  parsing method io.nats.client.NUID.<init>(NUID.java:74) reachable via the parsing context
    at static root method.(Unknown Source)


Error: Discovered unresolved type during parsing: sun.security.x509.X509Key. This error is reported at image build time because class net.i2p.crypto.eddsa.EdDSAEngine is registered for linking at image build time by command line and command line.
Error encountered while parsing net.i2p.crypto.eddsa.EdDSAEngine.engineInitVerify(EdDSAEngine.java:147) 
Parsing context:
   at java.security.SignatureSpi.engineInitVerify(SignatureSpi.java:99)
   at java.security.Signature.initVerify(Signature.java:529)
   at java.security.Signature$1.initVerify(Signature.java:132)
   at sun.security.util.SignatureUtil.initVerifyWithParam(SignatureUtil.java:172)
   at sun.security.x509.X509CertImpl.verify(X509CertImpl.java:354)
   at sun.security.x509.X509CertImpl.verify(X509CertImpl.java:308)
   at sun.security.tools.KeyStoreUtil.signedBy(KeyStoreUtil.java:80)
   at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2198)
   at java.security.KeyStore.load(KeyStore.java:1500)
   at io.vertx.core.net.impl.KeyStoreHelper.toKeyManagerFactory(KeyStoreHelper.java:165)
   at io.vertx.core.net.impl.KeyStoreHelper.<init>(KeyStoreHelper.java:144)
   at io.vertx.core.net.KeyStoreOptionsBase.getHelper(KeyStoreOptionsBase.java:188)
   at io.vertx.core.net.KeyStoreOptionsBase.loadKeyStore(KeyStoreOptionsBase.java:200)
   at io.quarkus.tls.runtime.keystores.JKSKeyStores.loadKeyStore(JKSKeyStores.java:153)
   at io.quarkus.tls.runtime.keystores.JKSKeyStores.verifyJKSTrustStoreStore(JKSKeyStores.java:44)
   at io.quarkus.tls.runtime.CertificateRecorder.verifyTrustStore(CertificateRecorder.java:126)
   at io.quarkus.tls.runtime.CertificateRecorder.verifyCertificateConfig(CertificateRecorder.java:85)
   at io.quarkus.tls.runtime.CertificateRecorder.validateCertificates(CertificateRecorder.java:48)
   at io.quarkus.deployment.steps.CertificatesProcessor$initializeCertificate877524439.deploy_0(Unknown Source)
   at io.quarkus.deployment.steps.CertificatesProcessor$initializeCertificate877524439.deploy(Unknown Source)
   at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
   at io.quarkus.runtime.Application.start(Application.java:101)
   at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:121)
   at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
   at com.oracle.svm.core.JavaMainWrapper.invokeMain(JavaMainWrapper.java:182)
   at com.oracle.svm.core.JavaMainWrapper.runCore0(JavaMainWrapper.java:236)
   at com.oracle.svm.core.JavaMainWrapper.doRun(JavaMainWrapper.java:303)
   at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
   at static root method.(Unknown Source)
```

**Comment by kompot2k** [comment]
The same problem, would be great to have native compilation

**Comment by Andro999b** [comment]
Related issue: https://github.com/quarkiverse/quarkus-sshd/issues/59

**Comment by MauriceVanVeen** [comment]
I tried compiling a native GraalVM binary some time ago and it was successful. Most issues I had was with installing GraalVM, musl and having zlib available :sweat_smile: 

`JAVA_HOME` is pointing to the GraalVM directory. Added the following GraalVM plugin in `build.gradle`:
```groovy
plugins {
  id 'org.graalvm.buildtools.native' version '0.10.3'
}
```

And the following settings with `--trace-object-instantiation` and `--initialize-at-run-time`, like is also mentioned in that error message:
```groovy
// https://www.graalvm.org/22.0/reference-manual/native-image/StaticImages/index.html
graalvmNative {
  binaries {
    main {
      setMainClass("com.example.demo.DemoApplication")
      agent {
        buildArgs(
          "--static",
          "--libc=musl",
          "--trace-object-instantiation=java.security.SecureRandom",
          "--initialize-at-run-time=io.nats.client.support.RandomUtils",
          "--initialize-at-run-time=io.nats.client.NUID"
        )
      }
    }
  }
}
```

It's just a simple Spring Boot app that subscribes on a `hello` subject and prints the message contents after doing a `nats pub hello "Hello, from GraalVM!"`:
```
$ ./demo

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/

 :: Spring Boot ::                (v3.3.3)

2024-12-05T10:25:58.741+01:00  INFO 14224 --- [demo] [           main] com.example.demo.DemoApplication         : Starting AOT-processed DemoApplication using Java 21.0.4 with PID 14224 (./spring-boot-graalvm/build/native/nativeCompile/demo started by X in ./spring-boot-graalvm/build/native/nativeCompile)
2024-12-05T10:25:58.741+01:00  INFO 14224 --- [demo] [           main] com.example.demo.DemoApplication         : No active profile set, falling back to 1 default profile: "default"
2024-12-05T10:25:58.745+01:00  INFO 14224 --- [demo] [           main] com.example.demo.DemoApplication         : Started DemoApplication in 0.013 seconds (process running for 0.016)
2024-12-05T09:26:00.690625Z: Hello, from GraalVM!
```

**Comment by MauriceVanVeen** [comment]
Btw, have you seen this section in the README? https://github.com/nats-io/nats.java?tab=readme-ov-file#integration-with-graalvm
Does that help as well?

**Comment by MauriceVanVeen** [comment]
@Andro999b, am getting a 404 on that repo, is it private?

**Comment by Andro999b** [comment]
@MauriceVanVeen my bad. No its public.

**Comment by Andro999b** [comment]
From further investigation, I found that Quarkus exposes `java.base` module partially. And since `sun.security.x509` is proprietary and might be removed in future releases, is not included by default. 
To fix `net.i2p.crypto:eddsa:0.3.0` issue, you need directly expose `sun.security.x509` by passing argument: 
 `-J--add-exports=java.base/sun.security.x509=ALL-UNNAMED` to the `native-build`.

**Comment by scottf** [comment]
@Andro999b have you followed the instructions here: https://github.com/nats-io/nats.java?tab=readme-ov-file#integration-with-graalvm

**Comment by scottf** [comment]
> the problem was in a way how Quarkus invokes `native-build`.
So can this be closed, or do you think there is something we can do in the library?

**Comment by Andro999b** [comment]
Since solution exists, this issue can be closed. But in my opinion you should concern to get rid of `net.i2p.crypto:eddsa:0.3.0`. Havent receive any update last 6 years. And modern java have already support Edwards-Curve algorithms throught JCA. And in worst case BouncyCastle exists.

**Comment by scottf** [comment]
@Andro999b Thank you. net.i2p.crypto:eddsa:0.3.0 is on my to-do list.
