### ISSUE TITLE
NATS consumers not pulling messages from Jetstream even though consumer status shows active. Restart of client application required as workaround to resolve the issue. [v2.10.18]

### ISSUE THREAD

**Issue by mohamedsaleem18** [nats-io/nats.java#1272]
### Observed behavior

NATS cluster :

- 3 Nodes
-  NATS version: 2.10.18

There are pending messages in the stream. Though consumers are connected to NATS, consumers are becoming stale. The workaround consists of purging the stream, deleting the affected consumers, and restarting the service they originate from. This recreates them in a healthy state to resolve the issue.  This issue occurs at least once every day.
Client side NATS configuration:

```hcl
nats {
  enabled = true
  address = "localhost:4222"
  bufferSize = 8
  timeout = 5000
  errorListener = "io.nats.client.impl.ErrorListenerLoggerImpl"
  streams {
    xxxStream {
      name = "lpsn32"
      subject = "xxx-response-details"
      consumerName = "xxxResponseHandler"
      handler = "xxxResponseHandler"
      batchSize = 1
      # pollingDuration is in ms
      pollingDuration = 100
    }
  }
  protocol = "stream"
}
```

### Expected behavior

Consumer should not go stale.  In case if Consumer is stale then NATS should automatically modify the consumer status as inactive or drop the consumer.

### Server and client version

NATS cluster :

- 3 Nodes. 
- NATS version :- 2.10.18

### Host environment

VM -  OS details
NAME="Oracle Linux Server"
VERSION="8.10"

### Steps to reproduce

1. Publish message to stream when consumer is connected.
2. Consumer will consume the messages without any issue.
3. If there is idle time or after long time, consumer goes stale.  Messages are pending in the stream but consumer are not consuming the message.  NATS shows consumer as active.

Please refer description section for workaround to resolve this issue.

**Comment by scottf** [comment]
@mohamedsaleem18 @burl21 Please review the code in this gist: https://gist.github.com/scottf/845fa51d8b78c299bb8f67c2ba34924f

The application is designed to try to recreate the stalling. it does the following
1. sets up the stream and consumer
2. Starts an admin thread to periodically report the state of the consumer
3. Starts a publish thread that publishes a bunch of messages up front and then loops to periodically publish a message. The time between publishes is a constant designed to be configured.
4. Start a simplified consumer that runs until program is terminated. It prints every time it gets a message.

**Comment by burl21** [comment]
While analyzing the consumer logs, we observed intermittent disconnection and reconnection to the server. These events
occurred due to a cluster upgrade process. When the pod restarted, it successfully established a connection to the
server. However, during the dispatcher registration phase, a connection error was encountered. This prevented the
dispatcher from being started. Since the error was not rethrown, the thread responsible for fetching messages did not
start.

### Pod Logs:

```log
2025-01-16T10:02:39.680Z [DEBUG] Nats connection event type: nats: lame duck mode
2025-01-16T10:02:51.113Z [WARN] Exception occurred, Connection: 81, Exception: java.io.IOException: Read channel closed.
2025-01-16T10:02:51.116Z [DEBUG] Nats connection event type: nats: connection disconnected
2025-01-16T10:02:51.137Z [DEBUG] Nats connection event type: nats: connection reconnected
2025-01-16T10:02:51.138Z [DEBUG] Nats connection event type: nats: subscriptions re-established
...

Pod restart...

...
2025-01-16T10:05:44.602Z [ERROR] Nats register error
java.io.IOException: Timeout or no response waiting for NATS JetStream server
...
at io.nats.client.impl.NatsJetStreamImpl.responseRequired(NatsJetStreamImpl.java:260)
at io.nats.client.impl.NatsJetStreamImpl.makeRequestResponseRequired(NatsJetStreamImpl.java:242)
at io.nats.client.impl.NatsJetStreamImpl._createConsumer(NatsJetStreamImpl.java:131)
at io.nats.client.impl.NatsJetStreamManagement.addOrUpdateConsumer(NatsJetStreamManagement.java:131)
```

### Code

We have created a Spring Boot Starter library to simplify the use of NATS.

The following code snippet highlights the issue within the dispatcher registration logic. Specifically, when an
exception is caught during the register method, the dispatcher is not started, leaving the consumer unable to fetch
messages:

```java
// Create Dispatcher
void register(RegisterArgs args) {
  try {
    var jsm = connection.jetStreamManagement();
    createStreamIfNotExists(jsm, args);
    createConsumerOrUpdate(jsm, args); // <- 👀 Error occurs here

    var pullOptions = PullSubscribeOptions.bind(stream, durable);
    var subscription = connection.jetStream().subscribe(args.subject(), pullOptions);
    var dispatcher = new NatsSubscriptionDispatcher(subscription, args.handler(), sharedTasksSemaphore);
    dispatchersExecutorService.execute(dispatcher);

    log.info("Subject: {} registered and dispatcher started.", args.subject());
  } catch (Exception e) {
    // ❌😭 Bug: Dispatcher is not started! As a result, it does not fetch messages!
    log.error("Nats register error", e);
  }
}

private void createStreamIfNotExists(JetStreamManagement jsm, RegisterArgs args)
  throws IOException, JetStreamApiException {
  if (jsm.getStreamNames(args.subject()).isEmpty()) {
    var configuration =
      StreamConfiguration.builder()
        .name(args.stream())
        .retentionPolicy(RetentionPolicy.WorkQueue)
        .storageType(natsProps.getStorageType())
        .discardPolicy(DiscardPolicy.Old)
        .subjects(args.subject())
        .denyDelete(true)
        .build();
    
    jsm.addStream(configuration);
    log.info("Stream with name {} created.", name);
  }
}

private void createConsumerOrUpdate(JetStreamManagement jsm, RegisterArgs args)
  throws IOException, JetStreamApiException {
  var consumer =
    ConsumerConfiguration.builder()
      .deliverPolicy(DeliverPolicy.All)
      .ackPolicy(AckPolicy.Explicit)
      .durable(args.consumer())
      .filterSubject(args.subject())
      .maxDeliver(natsProps.getMaxDeliver())
      .ackWait(natsProps.getAckTimeout())
      .build();

  jsm.addOrUpdateConsumer(args.stream(), consumer); // <- 👀 Error occurs here
}
```

Shouldn’t `connection.jetStreamManagement()` or `jsm.getStreamNames(subject)` throw some kind of connection error?

@scottf Thanks for your help, and apologies for any inconvenience caused!

**Comment by scottf** [comment]
The jetstream management object is just a functional wrapper - it doesn't actually do any io on creation, but it uses the connection it was given. If register fails, try pausing and retrying in a few seconds. That should give any connection time to reset. Once the [simplified] consumer is running, it is very resilient. If there is a disconnection, it will go into a failure loop where it periodically retries (based on the idleHeartbeat inside the simplified consumer).

getStreamNames throws a timeout, correct? Maybe also something to retry. 

Using the client requires a lot of error handling for all the disconnection edge cases. The client does a lot for core subscriptions, some old style subscriptions and all simplification subscriptions, but it does not do everything for you.
