### ISSUE TITLE
Spring App unable to connect to NATS in K8S (works in Docker)

### ISSUE THREAD

**Issue by wallyqs** [nats-io/nats.java#281]
Issue reported by https://github.com/hsarena in slack, repo with issue at: https://github.com/jibitters/notifier

Java client NATS running under the following scenario appears to not being able to finish connecting properly.

Kubernetes: 1.16.3
CNI: Flannel
NATS Operator: 0.6.0
NATS: 2.1.2
jnats: 2.6.6

Exception:

```
Error creating bean with name 'createConnection' defined in class path resource [ir/jibit/notifier/config/nats/NatsConfiguration.class]: 
Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.nats.client.Connection]: Factory method 'createConnection' threw exception; nested exception is java.io.IOException: Unable to connect to NATS servers: nats://nats:4222, 10.244.0.135:4222, 10.244.2.115:4222, 10.244.1.131:4222.
```

Taking a tcpdump from the network traffic and tracing, it looks like the client is being able to receive the INFO protocol, although not sending/flushing the CONNECT and PING protocols commands afterwards

```sh
12:06:40.049213 IP 10.244.2.164.49584 > 10.107.16.129.4222: Flags [S], seq 3288009728, win 28200, options [mss 1410,sackOK,TS val 4019544892 ecr 0,nop,wscale 2], length 0

12:06:40.049857 IP 10.107.16.129.4222 > 10.244.2.164.49584: Flags [S.], seq 4057289085, ack 3288009729, win 27960, options [mss 1410,sackOK,TS val 4018793430 ecr 4019544892,nop,wscale 7], length 0

12:06:40.049888 IP 10.244.2.164.49584 > 10.107.16.129.4222: Flags [.], ack 1, win 7050, options [nop,nop,TS val 4019544893 ecr 4018793430], length 0

# INFO protocol received, TCP connection itself appears to be OK
12:06:40.050768 IP 10.107.16.129.4222 > 10.244.2.164.49584: Flags [P.], seq 1:366, ack 1, win 219, options [nop,nop,TS val 4018793431 ecr 4019544893], length 365
INFO {"server_id":"NAVQVNJDRG7NJOPQ3H6OFIR4KJCMOBDWLBK4NEFMNKDWJ6ADKSRV724F","server_name":"NAVQVNJDRG7NJOPQ3H6OFIR4KJCMOBDWLBK4NEFMNKDWJ6ADKSRV724F","version":"2.1.2","proto":1,"git_commit":"679beda","go":"go1.12.13","host":"0.0.0.0","port":4222,"max_payload":1048576,"client_id":394,"connect_urls":["10.244.0.135:4222","10.244.2.115:4222","10.244.1.131:4222"]} 

12:06:40.050783 IP 10.244.2.164.49584 > 10.107.16.129.4222: Flags [.], ack 366, win 7318, options [nop,nop,TS val 4019544894 ecr 4018793431], length 0

# Connection closing due to internal deadline from client
12:06:42.039894 IP 10.244.2.164.49584 > 10.107.16.129.4222: Flags [F.], seq 1, ack 366, win 7318, options [nop,nop,TS val 4019546883 ecr 4018793431], length 0

12:06:42.040843 IP 10.107.16.129.4222 > 10.244.2.164.49584: Flags [F.], seq 366, ack 2, win 219, options [nop,nop,TS val 4018795421 ecr 4019546883], length 0

12:06:42.040868 IP 10.244.2.164.49584 > 10.107.16.129.4222: Flags [.], ack 367, win 7318, options [nop,nop,TS val 4019546884 ecr 4018795421], length 0
```

**Comment by wallyqs** [comment]
Reproduced issue as follows:

```sh
curl -sSL https://nats-io.github.io/k8s/setup.sh | sh -s -- --without-auth
kubectl run notifier --generator=run-pod/v1 --image=jibitters/notifier:0.0.1-SNAPSHOT -- --nats.servers="nats://nats:4222"
```


```sh
kubectl logs notifier --follow

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.1.RELEASE)

2019-12-05 22:18:48.340  INFO 1 --- [           main] ir.jibit.notifier.ApplicationKt          : Starting ApplicationKt v0.0.1-SNAPSHOT on notifier with PID 1 (/app/app.jar started by root in /app)
2019-12-05 22:18:48.346  INFO 1 --- [           main] ir.jibit.notifier.ApplicationKt          : No active profile set, falling back to default profiles: default
2019-12-05 22:18:53.187  WARN 1 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'createConnection' defined in class path resource [ir/jibit/notifier/config/nats/NatsConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.nats.client.Connection]: Factory method 'createConnection' threw exception; nested exception is java.io.IOException: Unable to connect to NATS servers: nats://nats:4222, 192.168.31.111:4222, 192.168.57.73:4222, 192.168.83.233:4222.
2019-12-05 22:18:53.189  INFO 1 --- [           main] i.j.n.config.nats.NatsConfiguration      : About to shutdown the Nats connection
2019-12-05 22:18:53.189  INFO 1 --- [           main] i.j.n.config.nats.NatsConfiguration      : Nats connection has been destroyed
2019-12-05 22:18:53.323  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-12-05 22:18:53.331 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'createConnection' defined in class path resource [ir/jibit/notifier/config/nats/NatsConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.nats.client.Connection]: Factory method 'createConnection' threw exception; nested exception is java.io.IOException: Unable to connect to NATS servers: nats://nats:4222, 192.168.31.111:4222, 192.168.57.73:4222, 192.168.83.233:4222.
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:645) ~[spring-beans-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:625) ~[spring-beans-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338) ~[spring-beans-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[spring-boot-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
	at ir.jibit.notifier.ApplicationKt.main(Application.kt:13) [classes!/:0.0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_232]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_232]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_232]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_232]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [app.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [app.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [app.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [app.jar:0.0.1-SNAPSHOT]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.nats.client.Connection]: Factory method 'createConnection' threw exception; nested exception is java.io.IOException: Unable to connect to NATS servers: nats://nats:4222, 192.168.31.111:4222, 192.168.57.73:4222, 192.168.83.233:4222.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:640) ~[spring-beans-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	... 27 common frames omitted
Caused by: java.io.IOException: Unable to connect to NATS servers: nats://nats:4222, 192.168.31.111:4222, 192.168.57.73:4222, 192.168.83.233:4222.
	at io.nats.client.impl.NatsConnection.connect(NatsConnection.java:236) ~[jnats-2.6.6.jar!/:2.6.6]
	at io.nats.client.impl.NatsImpl.createConnection(NatsImpl.java:29) ~[jnats-2.6.6.jar!/:2.6.6]
	at io.nats.client.Nats.createConnection(Nats.java:247) ~[jnats-2.6.6.jar!/:2.6.6]
	at io.nats.client.Nats.connect(Nats.java:164) ~[jnats-2.6.6.jar!/:2.6.6]
	at ir.jibit.notifier.config.nats.NatsConfiguration.createConnection(NatsConfiguration.kt:51) ~[classes!/:0.0.1-SNAPSHOT]
	at ir.jibit.notifier.config.nats.NatsConfiguration$$EnhancerBySpringCGLIB$$bcf359df.CGLIB$createConnection$0(<generated>) ~[classes!/:0.0.1-SNAPSHOT]
	at ir.jibit.notifier.config.nats.NatsConfiguration$$EnhancerBySpringCGLIB$$bcf359df$$FastClassBySpringCGLIB$$3e8db9fc.invoke(<generated>) ~[classes!/:0.0.1-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at ir.jibit.notifier.config.nats.NatsConfiguration$$EnhancerBySpringCGLIB$$bcf359df.createConnection(<generated>) ~[classes!/:0.0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_232]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_232]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_232]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_232]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	... 28 common frames omitted
```

**Comment by wallyqs** [comment]
Same issue occurs when running against the demo server:

```sh
kubectl run notifier --generator=run-pod/v1 --image=jibitters/notifier:0.0.1-SNAPSHOT -- --nats.servers="nats://demo.nats.io:4222"
```

**Comment by wallyqs** [comment]
The problem seems to be isolated to running within Kubernetes for some reason... Docker is fine:
```
 docker run jibitters/notifier:0.0.1-SNAPSHOT --nats.servers="nats://demo.nats.io:4222"

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.1.RELEASE)

2019-12-06 19:24:02.097  INFO 1 --- [           main] ir.jibit.notifier.ApplicationKt          : Starting ApplicationKt v0.0.1-SNAPSHOT on badf02b77533 with PID 1 (/app/app.jar started by root in /app)
2019-12-06 19:24:02.182  INFO 1 --- [           main] ir.jibit.notifier.ApplicationKt          : No active profile set, falling back to default profiles: default
2019-12-06 19:24:13.761  INFO 1 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 3 endpoint(s) beneath base path '/actuator'
2019-12-06 19:24:16.491  INFO 1 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port(s): 8080
2019-12-06 19:24:16.509  INFO 1 --- [           main] ir.jibit.notifier.ApplicationKt          : Started ApplicationKt in 19.418 seconds (JVM running for 21.659)
```

Connection is present as well when starting in Docker

```js
    {
      "cid": 9346,
      "ip": "67.188.40.234",
      "port": 50784,
      "start": "2019-12-06T14:24:10.861370913-05:00",
      "last_activity": "2019-12-06T14:24:11.022566421-05:00",
      "rtt": "31ms",
      "uptime": "2m59s",
      "idle": "2m59s",
      "pending_bytes": 0,
      "in_msgs": 0,
      "out_msgs": 0,
      "in_bytes": 0,
      "out_bytes": 0,
      "subscriptions": 1,
      "lang": "java",
      "version": "2.6.6"
    }
```

**Comment by alimate** [comment]
@wallyqs We were using a custom `ThreadPoolExecutor` to mimic a `fixed thread pool` like behavior:
```kotlin
val loopExecutor = ThreadPoolExecutor(properties.poolSize, properties.poolSize, 0, MILLISECONDS,
            LinkedBlockingQueue(), PrefixedThreadFactory(properties.threadPrefix))
``` 

In our K8S setup, we had one thread executing the main event loop. Apparently, the main thread gets blocked in initial ping/pong. Therefore, other events queued inside that `LinkedBlockingQueue `.

**Comment by wallyqs** [comment]
@alimate glad to hear you found the root cause! ok will close then
