### ISSUE TITLE
Connection failed using nkey file

### ISSUE THREAD

**Issue by sammy007** [nats-io/nats.java#282]
Nats: 2.1.2
jnats: 2.6.6
javac: 13.0.2

```java
AuthHandler h = Nats.credentials(null, "/path/to/seed.nkey");
Options options = new Options.Builder().
        authHandler(h).
        server("nats://host:port").
        traceConnection().
        verbose().
        build();

System.out.println(options.getAuthHandler().getID());
try {
    Connection nc = Nats.connect(options);
} catch (IOException e) {
    e.printStackTrace();
}
```

`System.out...` prints public key so I assume options are fine.

```
[13:41:21.363004] connect trace: creating connection object
[13:41:21.382412] connect trace: creating executors
[13:41:21.383195] connect trace: creating reader and writer
[13:41:21.386027] connect trace: connection object created
[13:41:21.386237] connect trace: starting connect loop
[13:41:21.387107] connect trace: setting status to connecting
[13:41:21.387294] connect trace: trying to connect to nats://host:port
[13:41:21.387468] connect trace: starting connection attempt, 2.000 (s) remaining
[13:41:21.388723] connect trace: waiting for reader, 1.999 (s) remaining
[13:41:21.389086] connect trace: waiting for writer, 1.998 (s) remaining
[13:41:21.389937] connect trace: cleaning pong queue, 1.998 (s) remaining
[13:41:21.390202] connect trace: connecting data port, 1.997 (s) remaining
[13:41:21.399639] connect trace: reading info, version and upgrading to secure if necessary, 1.988 (s) remaining
[13:41:21.508906] connect trace: starting reader, 1.879 (s) remaining
[13:41:21.509429] connect trace: starting writer, 1.878 (s) remaining
[13:41:21.515089] connect trace: sending connect message, 1.872 (s) remaining
[13:41:21.521665] connect trace: setting status to disconnected
[13:41:21.521849] connect trace: connection failed, closing to cleanup

java.io.IOException: Unable to connect to NATS servers: nats://host:port.
	at io.nats.client.impl.NatsConnection.connect(NatsConnection.java:236)
	at io.nats.client.impl.NatsImpl.createConnection(NatsImpl.java:29)
	at io.nats.client.Nats.createConnection(Nats.java:247)
	at io.nats.client.Nats.connect(Nats.java:164)
...
```

It will work with static seed and inline handler:

```java
char[] seed = "S...".toCharArray();
NKey theNKey = NKey.fromSeed(seed);
Options options = new Options.Builder().
        server("nats://host:port").
        authHandler(new AuthHandler() {
            public char[] getID() {
                try {
                    return theNKey.getPublicKey();
                } catch (GeneralSecurityException | IOException | NullPointerException ex) {
                    return null;
                }
            }

            public byte[] sign(byte[] nonce) {
                try {
                    return theNKey.sign(nonce);
                } catch (GeneralSecurityException | IOException | NullPointerException ex) {
                    return null;
                }
            }

            public char[] getJWT() {
                return null;
            }
        }).
        build();
```

**Comment by sammy007** [comment]
It works if I change

```java
Nats.credentials(null, "/path/to/seed.nkey");
```
to
```java
Nats.credentials("/path/to/seed.nkey", "/path/to/seed.nkey");
```
But it seems that is not correct way.

**Comment by kozlovic** [comment]
If you use `.credentials()` with 2 files, then they should be both be specified. Otherwise use this version instead: https://github.com/nats-io/nats.java/blob/1874536f0bc0de0d6587b93e1c9250077d9802c4/src/main/java/io/nats/client/Nats.java#L217

**Comment by sammy007** [comment]
This requires creds file to contain JWT. Looks like there is no way to use this lib without JWT. But I can do that with `nats.go`, that's confusing.

**Comment by kozlovic** [comment]
Have you tried with https://github.com/nats-io/nats.java/blob/1874536f0bc0de0d6587b93e1c9250077d9802c4/src/main/java/io/nats/client/Nats.java#L241, it looks like you could provide just the nkey and live the JWT empty.

**Comment by sammy007** [comment]
Of course I can provide nkey using `char[]` but I need it via file, with memory cleanup, etc.

**Comment by kozlovic** [comment]
@sammy007 I have attempted to solve this issue with #286. Let me know if this what you had in mind. We will see if the PR is accepted.

**Comment by sammy007** [comment]
Yes my goal was optional JWT.
