### ISSUE TITLE
Issue in discovered server list in case of DNS entry

### ISSUE THREAD

**Issue by nagukothapalli** [nats-io/nats.java#329]
In the case of DNS as nats endpoint, while NATS producer/consumer discovering list the servers, Noticing  DNS entry also one of the servers discovered Servers list. This could an issue in case of if want to route the traffic from one cluster to another cluster in case of DR activity.

**Sample Log:**
``` Cnnected/ReConnected NATS Server: [tls://dns:4222, server1:4222, server2:4222,server3:4222, server4:4222, server5:4222] - Event :nats: connection opened ```

So the issue here, for example, if all the servers in the NATS clusters went down in the respective cluster. the produce/consumer is thinking DNS entry has a valid server and it keeps on trying and it is hanging there itself. and somehow producer/consumer always considering this DNS entry is healthy even though no active brokers in the clusters.

**Comment by ColinSullivan1** [comment]
Hi @nagukothapalli, I have a few questions that will help us narrow this down...

- Is the DNS entry is provided by `--cluster_advertise` in one of the NATS servers?
- Can you elaborate on the producers/consumers thinking the DNS entry is healthy? What is the client doing?  For example does the client hang on reconnect, report a successful connection, or does not honor reconnect attempts?

**Comment by nagukothapalli** [comment]
Hi @ColinSullivan1 

- Is the DNS entry is provided by --cluster_advertise in one of the NATS servers?
    No,  we haven't used --cluster_advertise.
- Can you elaborate on the producers/consumers thinking the DNS entry is healthy? What is the client doing? For example, does the client hang on reconnect, report a successful connection, or do not honor reconnect attempts?
  ``` 
client  is keep on trying for the connection, and it is getting below exception
java.io.IOException: java.net.ConnectException: Connection refused: connect
[13:32:33.542] connect trace: starting connection attempt, 5.000 (s) remaining
	at io.nats.client.impl.SocketDataPort.connect(SocketDataPort.java:63)
	at io.nats.client.impl.NatsConnection.tryToConnect(NatsConnection.java:415)
	at io.nats.client.impl.NatsConnection.reconnect(NatsConnection.java:286)
	at io.nats.client.impl.NatsConnection.closeSocket(NatsConnection.java:607)
	at io.nats.client.impl.NatsConnection.lambda$handleCommunicationIssue$2(NatsConnection.java:564)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at io.nats.client.impl.SocketDataPort.connect(SocketDataPort.java:58)
	... 9 more
13:32:33.543] connect trace: waiting for reader, 4.998 (s) remaining ```


**Here are the steps I have followed.**

- set it up two broker cluster and  how brokers endpoints will be discovered with DNS name (dnsname:4224)

- start the producer and observed the below logs 

```Discovered Server(s) : [tls://DNS:4224, sever1:4224, server2:4224] ( As I mentioned I am noticing DNS entry in the discovered servers list.) ```

- Stop the Server 1 with LDM mode, noted discovered servers list got updated in producer connection listener and noticed traffic picked by server2

```INFO  - Connected/ReConnected NATS Server: [tls://DNS:4224, server2:4224] - Event :nats: connection reconnected```
Stop Server 2 with LDM mode. and getting below exceptions continuously.

``` 
[13:41:57.763] connect trace: waiting for writer	at io.nats.client.impl.SocketDataPort.connect(SocketDataPort.java:63)
	at io.nats.client.impl.NatsConnection.tryToConnect(NatsConnection.java:415)
	at io.nats.client.impl.NatsConnection.reconnect(NatsConnection.java:286)
	at io.nats.client.impl.NatsConnection.closeSocket(NatsConnection.java:607)
	at io.nats.client.impl.NatsConnection.lambda$handleCommunicationIssue$2(NatsConnection.java:564)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at io.nats.client.impl.SocketDataPort.connect(SocketDataPort.java:58)
	... 9 more
, 4.998 (s) remaining
```

**Comment by ColinSullivan1** [comment]
We're looking into this, thanks @nagukothapalli.  Can you confirm which connection URL is problematic here?  I'm assuming the DNS url, but just want to cover all the bases.

**Comment by nagukothapalli** [comment]
it's with  DNS URL

**Comment by ColinSullivan1** [comment]
Can you share the connection options that you are using to connect...

e.g. 
```java
        Options options = new Options.Builder().
                                server("nats://localhost:4222").
                                maxReconnects(-1).
                                reconnectWait(Duration.ofMillis(100)).
                                connectionListener(new reconnectDNSHandler()).
                                traceConnection().
                                build();

        Connection c = Nats.connect(options);
```

**Comment by ColinSullivan1** [comment]
I was able to finally reproduce this using invalid ports against a demo server of ours.  What was interesting was that under other DNS entries without NATS servers running, I wasn't seeing the condition.  

It seems under certain error conditions the client will rapidly cycle through all of the servers.  The good news is that your client will eventually reconnect.

I'll continue to look into this.

**Comment by ColinSullivan1** [comment]
An update...  The exceptions you are seeing (assuming they are from the error listener) are accurate and expected.  I did see servers cycle between the DNS server and non-DNS servers, and did not encounter a hang.  However, the reconnect delay was not being honored, so you were likely seeing many more attempts than you should have.

Also, remember that the reconnect attempts for java differ than the other clients - the java client uses it as an aggregate count rather than a per-server count.  I'd just set it at a very high number and alert when it's triggered.

Here's the code I used to recreate this:
```java
    private class reconnectDNSHandler implements ConnectionListener, ErrorListener {

        @Override
        public void connectionEvent(Connection conn, Events type) {

            if (type == Events.CONNECTED)
            {
                System.out.println("Connected to " + conn.getConnectedUrl()
                    + ".  Servers are: " + conn.getServers());
            }
            if (type == Events.DISCOVERED_SERVERS)
            {
                System.out.println("Discovered Servers.  Servers are: " + conn.getServers());
            }
            if (type == Events.RECONNECTED)
            {
                System.out.println("Reconnected.  Servers are: " + conn.getServers());
            }
            if (type == Events.DISCONNECTED)
            {
                System.out.println("Disconnected.");
            }
            if (type == Events.CLOSED)
            {
                System.out.println("Closed.");
            }
        }

        @Override
        public void errorOccurred(Connection conn, String error) {
            System.out.println("Connection error: " + error);
        }

        @Override
        public void exceptionOccurred(Connection conn, Exception exp) {
            System.out.println("Connection Exception: " + exp.getMessage());
        }

        @Override
        public void slowConsumerDetected(Connection conn, Consumer consumer) {
            // NOOP
        }

    }

    @Test
    public void testReconnectToDNSwithNoServers() throws IOException, InterruptedException {
        int port = NatsTestServer.nextPort();
        reconnectDNSHandler handler = new reconnectDNSHandler();
        Options options = new Options.Builder().
                                server("nats://localhost:"+port+",nats://demo.nats.io:12345").
                                maxReconnects(15).
                                connectionTimeout(Duration.ofSeconds(5)).
                                reconnectWait(Duration.ofMillis(500)).
                                connectionListener(handler).
                                errorListener(handler).
                                traceConnection().
                                build();

        NatsTestServer ts = new NatsTestServer(port, true);
        Connection c = Nats.connect(options);

        // Manually close or lame duck the server here...

        try {
            Thread.sleep(120000);
        } catch (Exception e) {
        }

        ts.close();

        ts = new NatsTestServer(port, false);
        Thread.sleep(10000);
        ts.close();
        c.close();
    }   
```

The reconnect wait timeout was not being honored, and will have a fix for that soon.

Can you provide logs that demonstrate a hang with the DNS server?  At the most you should see a connection timeout (looks like 5s in your test) and then the client should move onto the next server.
