### ISSUE TITLE
Breaking changes of multiple configurations from Long to Integer

### ISSUE THREAD

**Issue by pY4x3g** [nats-io/nats.java#684]
After upgrading to a newer version of the nats java library my application crashes because some properties where changed to be parsed as an integer rather than a long as before. The first crash I get for the `max_deliver` property. I used Long.MAX_VALUE for many properties for the streams and consumers.

Is this an intended behavior? To fix this issue we will have to remove and recreate the streams and consumers.
The stacktrace I get:
```
java.lang.NumberFormatException: For input string: "9223372036854775807"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at io.nats.client.support.JsonUtils.readInteger(JsonUtils.java:603)
	at io.nats.client.api.ConsumerConfiguration.<init>(ConsumerConfiguration.java:137)
	at io.nats.client.api.ConsumerInfo.<init>(ConsumerInfo.java:54)
	at io.nats.client.api.ConsumerInfo.<init>(ConsumerInfo.java:44)
	at io.nats.client.impl.NatsJetStreamImplBase._getConsumerInfo(NatsJetStreamImplBase.java:48)
	at io.nats.client.impl.NatsJetStream.lookupConsumerInfo(NatsJetStream.java:608)
	at io.nats.client.impl.NatsJetStream.createSubscription(NatsJetStream.java:293)
	at io.nats.client.impl.NatsJetStream.subscribe(NatsJetStream.java:596)
```

Latest tested jnats version with crash: 2.15.4
Current jnats version without an issue: 2.15.1

**Comment by scottf** [comment]
Sorry, fixing.

**Comment by scottf** [comment]
@pY4x3g Releasing 2.15.5 addressing this.

**Comment by pY4x3g** [comment]
Thank you very much for the quick fix!
